apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmp-chart.deploymentName" . }}
  labels:
    {{- include "nmp-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "nmp-chart.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nmp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "nmp-chart.annotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nmp-chart.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: 'true'
    spec:
      {{- with .Values.dns }}
      dnsPolicy: {{ .dnspolicy }}
      dnsConfig:
        {{- with .nameservers}}
        nameservers:
          {{- toYaml . | nindent 8}}
        {{- end }}
        {{- with .searches }} 
        searches:
          {{- toYaml . | nindent 8}}
        {{- end }} 
      {{- end }}
      {{- with .Values.hostAliases}}
      hostAliases:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nmp-chart.fullName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP     
            - name: metrics
              containerPort: 8081
              protocol: TCP 
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8080
          readinessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8080
          env: 
            {{- range $key, $value := .Values.env}}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
