{{- $fullName := include "nmp-chart.deploymentName" $ -}}
{{- range .Values.ingress.ingresses -}}
{{- $ingressClassName := coalesce .className $.Values.ingress.className -}}
{{- $dnsSuffix := coalesce .dnsSuffix $.Values.ingress.dnsSuffix -}}
{{- $annotations := (merge (.annotations | default dict) ($.Values.ingress.annotations | default dict)) -}}
{{- if and $ingressClassName (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $annotations "kubernetes.io/ingress.class" $ingressClassName}}
  {{- end }}
{{- end }}
---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName -}}
  {{- if .name -}}
    -{{ .name }}
  {{- end }}
  labels:
    {{- include "nmp-chart.labels" $ | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressClassName (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range $host:=.hosts }}
        - {{ $host }}.{{ $.Values.ingress.tenantName }}.{{ $dnsSuffix }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host }}.{{ $.Values.ingress.tenantName }}.{{ $dnsSuffix }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
