apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmp-chart.fullName" . }}
  labels:
    {{- include "nmp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "nmp-chart.selectorLabels" . | nindent 4 }}
