apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nmp-chart.fullName" . }}
spec:
  selector:
    matchLabels:
      {{- include "nmp-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics