apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nmp-chart.fullName" . }}
  annotations:
  {{- with  $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nmp-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics