{{ if .Values.prometheus -}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nmp-chart.fullName" . }}
  annotations:
  {{- include "nmp-chart.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nmp-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
{{- end }}