apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmp-chart.deploymentName" . }}
  labels:
    {{- include "nmp-chart.labels" . | nindent 4 }}
  annotations: 
    {{- include "nmp-chart.annotations" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.prometheus }}
    - port: {{ .port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "nmp-chart.selectorLabels" . | nindent 4 }}
